<p>In page help is indicated by the <span class="info" title="Tooltip Help">&nbsp;</span> icon or a blue border around an entry field.</p>
<p>You now have a number of new widgets prefixed with the word 'Site' that operate the same as the standard WordPress plugins, just with the addition of a 'Site' option in the setup.
You are able to select any Site on the Multisite installation that you have administration access to.</p>
<p>
 Just select the site and click 'save' now the widget is operating as if it was on the other site, enabling you to display for example the blogroll or recent posts from the main blog.
 </p>